CRITICAL - 2025-03-24 01:08:03 --> ErrorException: Undefined variable $totalTime
[Method: GET, Route: /]
in SYSTEMPATH\Debug\Toolbar\Views\toolbar.tpl.php on line 46.
 1 SYSTEMPATH\Debug\Toolbar\Views\toolbar.tpl.php(46): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $totalTime', 'C:\\xampp\\htdocs\\matatech-crud\\system\\Debug\\Toolbar\\Views\\toolbar.tpl.php', 46)
 2 SYSTEMPATH\Debug\Toolbar.php(533): include('C:\\xampp\\htdocs\\matatech-crud\\system\\Debug\\Toolbar\\Views\\toolbar.tpl.php')
 3 SYSTEMPATH\Debug\Toolbar.php(496): CodeIgniter\Debug\Toolbar->format([...], 'html')
 4 APPPATH\Config\Events.php(47): CodeIgniter\Debug\Toolbar->respond()
 5 SYSTEMPATH\Events\Events.php(155): CodeIgniter\Events\Events::Config\{closure}()
 6 SYSTEMPATH\CodeIgniter.php(339): CodeIgniter\Events\Events::trigger('pre_system')
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-03-24 01:31:13 --> ErrorException: Undefined array key "titlo"
[Method: GET, Route: tasks]
in APPPATH\Views\tasks\index.php on line 30.
 1 APPPATH\Views\tasks\index.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "titlo"', 'C:\\xampp\\htdocs\\matatech-crud\\app\\Views\\tasks\\index.php', 30)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\matatech-crud\\app\\Views\\tasks\\index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('tasks/index', [], true)
 5 APPPATH\Controllers\TaskController.php(14): view('tasks/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TaskController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TaskController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-03-24 01:31:13 --> ErrorException: Undefined array key "titlo"
[Method: GET, Route: tasks]
in APPPATH\Views\tasks\index.php on line 30.
 1 APPPATH\Views\tasks\index.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "titlo"', 'C:\\xampp\\htdocs\\matatech-crud\\app\\Views\\tasks\\index.php', 30)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\matatech-crud\\app\\Views\\tasks\\index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('tasks/index', [], true)
 5 APPPATH\Controllers\TaskController.php(14): view('tasks/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TaskController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TaskController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-03-24 01:31:14 --> ErrorException: Undefined array key "titlo"
[Method: GET, Route: tasks]
in APPPATH\Views\tasks\index.php on line 30.
 1 APPPATH\Views\tasks\index.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "titlo"', 'C:\\xampp\\htdocs\\matatech-crud\\app\\Views\\tasks\\index.php', 30)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\matatech-crud\\app\\Views\\tasks\\index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('tasks/index', [], true)
 5 APPPATH\Controllers\TaskController.php(14): view('tasks/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TaskController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TaskController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-03-24 03:06:38 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\matatech-crud\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\matatech-crud\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'tasks_db', 3306, '', 0)
#1 C:\xampp\htdocs\matatech-crud\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\matatech-crud\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\matatech-crud\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\matatech-crud\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\matatech-crud\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\matatech-crud\app\Controllers\TaskController.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\matatech-crud\system\CodeIgniter.php(933): App\Controllers\TaskController->index()
#8 C:\xampp\htdocs\matatech-crud\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TaskController))
#9 C:\xampp\htdocs\matatech-crud\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\matatech-crud\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\matatech-crud\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\matatech-crud\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\matatech-crud\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\matatech-crud\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\matatech-crud\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\matatech-crud\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\matatech-crud\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\matatech-crud\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\matatech-crud\app\Controllers\TaskController.php(12): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\matatech-crud\system\CodeIgniter.php(933): App\Controllers\TaskController->index()
#7 C:\xampp\htdocs\matatech-crud\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TaskController))
#8 C:\xampp\htdocs\matatech-crud\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\matatech-crud\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\matatech-crud\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\matatech-crud\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-03-24 03:06:38 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
[Method: GET, Route: tasks]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tasks`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TaskController.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TaskController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TaskController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-03-24 18:51:13 --> ErrorException: Undefined array key "Título"
[Method: GET, Route: tasks]
in APPPATH\Views\tasks\index.php on line 20.
 1 APPPATH\Views\tasks\index.php(20): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "Título"', 'C:\\xampp\\htdocs\\matatech-crud\\app\\Views\\tasks\\index.php', 20)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\matatech-crud\\app\\Views\\tasks\\index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('tasks/index', [], true)
 5 APPPATH\Controllers\TaskController.php(14): view('tasks/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TaskController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TaskController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-03-24 19:07:58 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\matatech-crud\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\matatech-crud\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `tasks` ...', 0)
#1 C:\xampp\htdocs\matatech-crud\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `tasks` ...')
#2 C:\xampp\htdocs\matatech-crud\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `tasks` ...')
#3 C:\xampp\htdocs\matatech-crud\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `tasks` ...', Array, false)
#4 C:\xampp\htdocs\matatech-crud\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\matatech-crud\system\BaseModel.php(1027): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\matatech-crud\system\Model.php(863): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\matatech-crud\app\Controllers\TaskController.php(55): CodeIgniter\Model->update('6', Array)
#8 C:\xampp\htdocs\matatech-crud\system\CodeIgniter.php(933): App\Controllers\TaskController->update('6')
#9 C:\xampp\htdocs\matatech-crud\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TaskController))
#10 C:\xampp\htdocs\matatech-crud\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\matatech-crud\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\matatech-crud\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\matatech-crud\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-03-24 19:07:59 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: tasks/update/6]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `tasks` SET `title` = :title:, `description` = :description:, `status` = :status:, `updated_at` = :updated_at:
WHERE `tasks`.`id` IN :tasks.id:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\TaskController.php(55): CodeIgniter\Model->update('6', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TaskController->update('6')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TaskController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-03-24 19:07:59 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `tasks` SET `title` = \'Fernando\', `description` = \'MadtechOw 2\', `status` = \'concluída\', `updated_at` = \'2025-03-24 19:07:58\'
WHERE `tasks`.`id` IN (\'6\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `tasks` SET `title` = \'Fernando\', `description` = \'MadtechOw 2\', `status` = \'concluída\', `updated_at` = \'2025-03-24 19:07:58\'
WHERE `tasks`.`id` IN (\'6\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `tasks` SET `title` = :title:, `description` = :description:, `status` = :status:, `updated_at` = :updated_at:
WHERE `tasks`.`id` IN :tasks.id:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\TaskController.php(55): CodeIgniter\Model->update('6', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TaskController->update('6')
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TaskController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-03-24 19:07:59 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `tasks` SET `title` = \'Fernando\', `description` = \'MadtechOw 2\', `status` = \'concluída\', `updated_at` = \'2025-03-24 19:07:58\'
WHERE `tasks`.`id` IN (\'6\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `tasks` SET `title` = \'Fernando\', `description` = \'MadtechOw 2\', `status` = \'concluída\', `updated_at` = \'2025-03-24 19:07:58\'
WHERE `tasks`.`id` IN (\'6\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `tasks` SET `title` = \'Fernando\', `description` = \'MadtechOw 2\', `status` = \'concluída\', `updated_at` = \'2025-03-24 19:07:58\'
WHERE `tasks`.`id` IN (\'6\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `tasks` SET `title` = :title:, `description` = :description:, `status` = :status:, `updated_at` = :updated_at:
WHERE `tasks`.`id` IN :tasks.id:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\TaskController.php(55): CodeIgniter\Model->update('6', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TaskController->update('6')
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TaskController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-03-24 22:32:41 --> CodeIgniter\HTTP\Exceptions\BadRequestException: The URI you submitted has disallowed characters: "(:num)"
[Method: GET, Route: tasks/%28:num%29]
in SYSTEMPATH\Router\Router.php on line 739.
 1 SYSTEMPATH\Router\Router.php(207): CodeIgniter\Router\Router->checkDisallowedChars('tasks/(:num)')
 2 SYSTEMPATH\CodeIgniter.php(832): CodeIgniter\Router\Router->handle('tasks/(:num)')
 3 SYSTEMPATH\CodeIgniter.php(455): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-03-24 22:33:12 --> CodeIgniter\HTTP\Exceptions\BadRequestException: The URI you submitted has disallowed characters: "(:num)"
[Method: GET, Route: tasks/%28:num%29]
in SYSTEMPATH\Router\Router.php on line 739.
 1 SYSTEMPATH\Router\Router.php(207): CodeIgniter\Router\Router->checkDisallowedChars('tasks/(:num)')
 2 SYSTEMPATH\CodeIgniter.php(832): CodeIgniter\Router\Router->handle('tasks/(:num)')
 3 SYSTEMPATH\CodeIgniter.php(455): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-03-24 22:34:02 --> CodeIgniter\HTTP\Exceptions\BadRequestException: The URI you submitted has disallowed characters: "(:num)"
[Method: DELETE, Route: tasks/%28:num%29]
in SYSTEMPATH\Router\Router.php on line 739.
 1 SYSTEMPATH\Router\Router.php(207): CodeIgniter\Router\Router->checkDisallowedChars('tasks/(:num)')
 2 SYSTEMPATH\CodeIgniter.php(832): CodeIgniter\Router\Router->handle('tasks/(:num)')
 3 SYSTEMPATH\CodeIgniter.php(455): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-03-24 22:34:44 --> CodeIgniter\HTTP\Exceptions\BadRequestException: The URI you submitted has disallowed characters: "(:num)"
[Method: DELETE, Route: tasks/%28:num%29]
in SYSTEMPATH\Router\Router.php on line 739.
 1 SYSTEMPATH\Router\Router.php(207): CodeIgniter\Router\Router->checkDisallowedChars('tasks/(:num)')
 2 SYSTEMPATH\CodeIgniter.php(832): CodeIgniter\Router\Router->handle('tasks/(:num)')
 3 SYSTEMPATH\CodeIgniter.php(455): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-03-24 22:35:05 --> CodeIgniter\HTTP\Exceptions\BadRequestException: The URI you submitted has disallowed characters: "(:num)"
[Method: GET, Route: tasks/%28:num%29]
in SYSTEMPATH\Router\Router.php on line 739.
 1 SYSTEMPATH\Router\Router.php(207): CodeIgniter\Router\Router->checkDisallowedChars('tasks/(:num)')
 2 SYSTEMPATH\CodeIgniter.php(832): CodeIgniter\Router\Router->handle('tasks/(:num)')
 3 SYSTEMPATH\CodeIgniter.php(455): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-03-24 22:44:41 --> Error: Call to undefined method App\Controllers\Api\TaskApiController::failtNotFound()
[Method: GET, Route: api/tasks/1]
in APPPATH\Controllers\Api\TaskApiController.php on line 24.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\TaskApiController->show('1')
 2 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\TaskApiController))
 3 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-03-24 22:49:04 --> ErrorException: Undefined property: App\Controllers\Api\TaskApiController::$reuest
[Method: PUT, Route: api/tasks/15]
in APPPATH\Controllers\Api\TaskApiController.php on line 43.
 1 APPPATH\Controllers\Api\TaskApiController.php(43): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Api\\TaskApiController::$reuest', 'C:\\xampp\\htdocs\\matatech-crud\\app\\Controllers\\Api\\TaskApiController.php', 43)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\TaskApiController->update('15')
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\TaskApiController))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
